version: '2.2'
services:
  elasticsearch:
    build: ./dockerfiles/elasticsearch_ik
    container_name: qq-elasticsearch
    restart: always
    environment:
    - cluster.name=qq-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - elasticsearch_local

  elasticsearch2:
    build: ./dockerfiles/elasticsearch_ik
    container_name: qq-elasticsearch2
    restart: always
    environment:
    - cluster.name=qq-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    - "discovery.zen.ping.unicast.hosts=qq-elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - esdata2:/usr/share/elasticsearch/data
    networks:
    - elasticsearch_local

  redis:
    image: redis
    container_name: qq-redis
    restart: always
    ports:
    - 6379:6379

  db:
    image: postgres:latest
    container_name: qq-db
    restart: always
    environment:
    - POSTGRES_DB=qq
    - POSTGRES_USER=dormon
    - POSTGRES_PASSWORD=dormon
    ports:
    - "0.0.0.0:5432:5432"

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  elasticsearch_local:
